springdoc:
  paths-to-match:
    - /api/**
  swagger-ui:
    urls:
      - name: Manually Configured API
        url: /openapi.yml
      - name: Code-Generated API
        url: /v3/api-docs
    urls-primary-name: Manually Configured API
    enabled: false
hello:
  default-name: Du lieber Mensch
  message: Halloechen, {}!
management:
  endpoints:
    web:
      exposure:
        include: '*'
        #health,info,beans,metrics,startup
      base-path: /health
  endpoint:
    health:
      show-details: always
      show-components: always
